// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-4MulX8yj_uad2AFm2qBJzQkuhoCq-T4',
    appId: '1:585999469969:web:32a8701becbcd3382f1e30',
    messagingSenderId: '585999469969',
    projectId: 'my-way-516c6',
    authDomain: 'my-way-516c6.firebaseapp.com',
    storageBucket: 'my-way-516c6.appspot.com',
    measurementId: 'G-PCFXT07GHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJigEN_kOHBamjhqYSLzIxn5kFsxvewl8',
    appId: '1:585999469969:android:5f37ee77e05064132f1e30',
    messagingSenderId: '585999469969',
    projectId: 'my-way-516c6',
    storageBucket: 'my-way-516c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd-kGfvIrA_-3xdHres_G91STlzNYfVQQ',
    appId: '1:585999469969:ios:b6f46c145083ef582f1e30',
    messagingSenderId: '585999469969',
    projectId: 'my-way-516c6',
    storageBucket: 'my-way-516c6.appspot.com',
    iosClientId: '585999469969-vcu9e10il2797rdrj48smi4fd3ui7060.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleads',
  );
}
